export const ENV = {
  AIMLAPI_KEY: process.env.AIMLAPI_KEY,
  LOGMEAL_API_KEY: process.env.LOGMEAL_API_KEY,
  EDAMAM_APP_KEY: process.env.EDAMAM_APP_KEY,
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  RAPIDAPI_KEY: process.env.RAPIDAPI_KEY,
};
