import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated17708102270921770810228053 implements MigrationInterface {
    name = 'AutoGenerated17708102270921770810228053'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_users_googleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_appleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_session_entity_routineId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_entity_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_entity_userId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_food_entries_userId_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_food_entries_userId_date_mealType"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('free', 'monthly', 'yearly', 'lifetime')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'canceled', 'expired', 'past_due', 'incomplete', 'trial')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "stripeCustomerId" character varying, "stripeSubscriptionId" character varying, "plan" "public"."subscriptions_plan_enum" NOT NULL DEFAULT 'free', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "currentPeriodStart" TIMESTAMP NOT NULL DEFAULT now(), "currentPeriodEnd" TIMESTAMP, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "canceledAt" TIMESTAMP, "trialEnd" TIMESTAMP, "price" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'usd', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fbdba4e2ac694cf8c9cecf4dc84" UNIQUE ("userId"), CONSTRAINT "REL_fbdba4e2ac694cf8c9cecf4dc8" UNIQUE ("userId"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbdba4e2ac694cf8c9cecf4dc8" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a48bd9e263c2a972787a60169b" ON "subscriptions" ("stripeCustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`ALTER TABLE "exercise_entity" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" ADD "imageUrl" text`);
        await queryRunner.query(`CREATE INDEX "IDX_f382af58ab36057334fb262efd" ON "users" ("googleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_60cea0d80c39eedaaaf5e21f17" ON "users" ("appleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_db6f24247e843e59be1de1b1fe" ON "routine_session_entity" ("routineId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_231af93c14eab9b726ae07fa6a" ON "routine_entity" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a164a09913b4d32c4d80b60022" ON "routine_entity" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf8759cb9bd6d554daba6969ad" ON "food_entries" ("userId", "date", "mealType") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e74a8457e1b9e2fc57c3d23b2" ON "food_entries" ("userId", "date") `);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e74a8457e1b9e2fc57c3d23b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf8759cb9bd6d554daba6969ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a164a09913b4d32c4d80b60022"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_231af93c14eab9b726ae07fa6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db6f24247e843e59be1de1b1fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60cea0d80c39eedaaaf5e21f17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f382af58ab36057334fb262efd"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" ADD "imageUrl" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a48bd9e263c2a972787a60169b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdba4e2ac694cf8c9cecf4dc8"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_food_entries_userId_date_mealType" ON "food_entries" ("userId", "date", "mealType") `);
        await queryRunner.query(`CREATE INDEX "IDX_food_entries_userId_date" ON "food_entries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_entity_userId_createdAt" ON "routine_entity" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_entity_userId" ON "routine_entity" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_session_entity_routineId_createdAt" ON "routine_session_entity" ("createdAt", "routineId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_appleId" ON "users" ("appleId") WHERE ("appleId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_users_googleId" ON "users" ("googleId") WHERE ("googleId" IS NOT NULL)`);
    }

}
