import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated17705556161051770555617360 implements MigrationInterface {
    name = 'AutoGenerated17705556161051770555617360'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_users_googleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_appleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_session_entity_routineId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_entity_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_routine_entity_userId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_food_entries_userId_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_food_entries_userId_date_mealType"`);
        await queryRunner.query(`CREATE INDEX "IDX_f382af58ab36057334fb262efd" ON "users" ("googleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_60cea0d80c39eedaaaf5e21f17" ON "users" ("appleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_db6f24247e843e59be1de1b1fe" ON "routine_session_entity" ("routineId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_231af93c14eab9b726ae07fa6a" ON "routine_entity" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a164a09913b4d32c4d80b60022" ON "routine_entity" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf8759cb9bd6d554daba6969ad" ON "food_entries" ("userId", "date", "mealType") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e74a8457e1b9e2fc57c3d23b2" ON "food_entries" ("userId", "date") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_2e74a8457e1b9e2fc57c3d23b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf8759cb9bd6d554daba6969ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a164a09913b4d32c4d80b60022"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_231af93c14eab9b726ae07fa6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db6f24247e843e59be1de1b1fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60cea0d80c39eedaaaf5e21f17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f382af58ab36057334fb262efd"`);
        await queryRunner.query(`CREATE INDEX "IDX_food_entries_userId_date_mealType" ON "food_entries" ("userId", "date", "mealType") `);
        await queryRunner.query(`CREATE INDEX "IDX_food_entries_userId_date" ON "food_entries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_entity_userId_createdAt" ON "routine_entity" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_entity_userId" ON "routine_entity" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_routine_session_entity_routineId_createdAt" ON "routine_session_entity" ("createdAt", "routineId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_appleId" ON "users" ("appleId") WHERE ("appleId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_users_googleId" ON "users" ("googleId") WHERE ("googleId" IS NOT NULL)`);
    }

}
