import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated17711828863491771182890289 implements MigrationInterface {
    name = 'AutoGenerated17711828863491771182890289'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_subscriptions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscriptions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscriptions_stripeCustomerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscriptions_status"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" ADD "imageUrl" text`);
        await queryRunner.query(`CREATE INDEX "IDX_fbdba4e2ac694cf8c9cecf4dc8" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a48bd9e263c2a972787a60169b" ON "subscriptions" ("stripeCustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a48bd9e263c2a972787a60169b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdba4e2ac694cf8c9cecf4dc8"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "exercise_entity" ADD "imageUrl" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_subscriptions_status" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_subscriptions_stripeCustomerId" ON "subscriptions" ("stripeCustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_subscriptions_userId" ON "subscriptions" ("userId") `);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
